# Generated by Django 4.2.7 on 2023-11-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='ToDoItem',
        ),
    ]
